.generate_template: &generate_definition
  script:
    - make generate
  stage: config
  artifacts:
    untracked: true

.compile_template: &compile_definition
  script:
    - make doc
  stage: build
  artifacts:
    untracked: true

.verify_template: &verify_definition
  script:
    - make test
  stage: test
  artifacts:
    paths:
      - "*.pdf"

stages:
    - config
    - build
    - test

generate:texlive2019:
    image: sergiud/texlive:2019
    <<: *generate_definition

generate:texlive2020:
    image: sergiud/texlive:2020
    <<: *generate_definition

generate:texlive2021:
    image: sergiud/texlive:2021
    <<: *generate_definition

compile:texlive2019:
    image: sergiud/texlive:2019
    <<: *compile_definition
    dependencies:
        - generate:texlive2019

compile:texlive2020:
    image: sergiud/texlive:2020
    <<: *compile_definition
    dependencies:
        - generate:texlive2020

compile:texlive2021:
    image: sergiud/texlive:2021
    <<: *compile_definition
    dependencies:
        - generate:texlive2021

verify:texlive2019:
    image: sergiud/texlive:2019
    <<: *verify_definition
    dependencies:
        - compile:texlive2019

verify:texlive2020:
    image: sergiud/texlive:2020
    <<: *verify_definition
    dependencies:
        - compile:texlive2020

verify:texlive2021:
    image: sergiud/texlive:2021
    <<: *verify_definition
    dependencies:
        - compile:texlive2021
