.generate_template: &generate_definition
  script:
    - make generate
  stage: config
  artifacts:
    untracked: true

.compile_template: &compile_definition
  script:
    - make doc
  stage: build
  artifacts:
    untracked: true

.verify_template: &verify_definition
  script:
    - make test
  stage: test
  artifacts:
    paths:
      - "*.pdf"

default:
  tags:
    - docker

stages:
    - config
    - build
    - test

generate:texlive2022:
    image: sergiud/texlive:2022
    <<: *generate_definition

compile:texlive2022:
    image: sergiud/texlive:2022
    <<: *compile_definition
    dependencies:
        - generate:texlive2022

verify:texlive2022:
    image: sergiud/texlive:2022
    <<: *verify_definition
    dependencies:
        - compile:texlive2022
